import java.lang.*;
import java.util.*;
class Main
{
    public static void main(String[] args)
    {
        int rno , gno;
        Scanner sr = new Scanner(System.in);
        Random rand = new Random();
       do
       {
            //Generates random integers from 0 to 10
            rno = rand.nextInt(10);
            System.out.print("Guess the number generated by the computer : ");
            gno = sr.nextInt();
            System.out.println("Random Number = " + rno);
            System.out.println("Your Number = " + gno);
            if(gno < rno)
                System.out.println("Your number is less than the random number");
            else if(gno > rno)
                System.out.println("Your number is greater than the random number");
            else
                System.out.println("Successfully you guessed the correct number");
       }while(rno != gno);
    }
}
